Feature/frontend forms
wizeline/ror-remotepayment-wizeline pull request #74
Opened 2022-03-16 17:57 UTC by fannypc11

closes #73

2022-03-16 20:03 UTC, georgexx009-wizeline requested changes

2022-03-16 20:07 UTC, gianpierregalvez1992 commented on remote_payment_front/src/utils/errorHandler.js
> +  console.log(err);
Debe ir este log?

2022-03-16 20:08 UTC, gianpierregalvez1992 commented on remote_payment_front/.gitignore
> +package-lock.json
Este archivo se recomienda que se suba al repo para poder trackear el cambio de versiones y para evitar conflictos al instalar los cambios deberíamos usar
`npm ci`

2022-03-16 20:11 UTC, fannypc11 commented on remote_payment_front/src/components/shared/UserForm.jsx
> +        {() => (
I though it'll look cleaner if we have all required functions together, outside the return block. What do you think?

2022-03-16 20:14 UTC, gianpierregalvez1992 commented on remote_payment_front/src/components/shared/TextField.module.css
> +  color: #b51f1f;
Creo que debería haber un archivo de variables con los colores y también me parece que podríamos usar styled components

2022-03-16 20:16 UTC, fannypc11 commented on remote_payment_front/src/components/shared/TextField.module.css
> +  color: #b51f1f;
Ya existe un archivo con las variables, lo voy a modificar.
Sobre usar styled components no estoy segura, me parece que modules nos da más flexibilidad con los estilos

2022-03-16 20:26 UTC, gianpierregalvez1992 reviewed
Lo del comentario de styled components es una recomendación ya que en la mayoría de clientes ya se usa

2022-03-16 20:26 UTC, gianpierregalvez1992 commented on remote_payment_front/src/pages/auth/Login.jsx
> +  '229053062186-nuroj3cfnb0qg4doceeiap58eu8e1282.apps.googleusercontent.com';
esto debería ir en el .env

2022-03-16 20:26 UTC, gianpierregalvez1992 commented on remote_payment_front/src/plugins/axios.js
Acá se podría adicionar el baseUrl y se llamaría desde el .env

2022-03-16 20:26 UTC, gianpierregalvez1992 commented on remote_payment_front/src/store/services/authService.js
> +      localStorage.setItem('user', JSON.stringify(response.user));
Almacenar el usuario no es tan recomendable, creo que si necesitamos el usuario podríamos consultar un api con el token

2022-03-17 00:17 UTC, fannypc11 commented on remote_payment_front/src/pages/contractor/Dashboard.jsx
> +export function AddUser() {
Este dashboard y su información es de prueba, se modificará con el contenido correspondiente

2022-03-17 00:20 UTC, fannypc11 commented on remote_payment_front/.gitignore
> +package-lock.json
No he usado `npm ci` ¿podríamos tener una llamada sólo para tener un overview de como se usaría? o tendrías algún articulo que me pudiera ayudar para entenderlo? me parece que son configuraciones que cambiaríamos en el proyecto

2022-03-17 13:15 UTC, gianpierregalvez1992 commented on remote_payment_front/.gitignore
> +package-lock.json
dale, si deseas podemos tener una llamada . Pero en resumen lo que hace npm ci es instalar las versiones especificas que tiene el .lock y el npm i instala las versiones que necesitemos para nuevos packages. Acá te dejo un link que encontré https://www.geeksforgeeks.org/difference-between-npm-i-and-npm-ci-in-node-js/ , igual lo de npm ci se va a usar cuando se descargue el proyecto por primera vez pero si necesitamos nuevos packages usaremos npm i

2022-03-17 22:29 UTC, georgexx009-wizeline commented on remote_payment_front/src/components/shared/UserForm.jsx
> +        {() => (
but if you remove line 35 and 47 would be the same right? because that callback is a functional component or this is a requirement from Formik?

2022-03-19 01:01 UTC, fannypc11 commented on remote_payment_front/src/components/shared/UserForm.jsx
> +        {() => (
No, it's just required when you want to use a helper from Formik, so I just removed it

2022-03-19 01:01 UTC, fannypc11 commented on remote_payment_front/src/components/shared/UserForm.jsx
> +  const validate = Yup.object({
Done

2022-03-19 01:02 UTC, fannypc11 commented on remote_payment_front/src/pages/auth/Login.jsx
> +  '229053062186-nuroj3cfnb0qg4doceeiap58eu8e1282.apps.googleusercontent.com';
Hecho

2022-03-19 01:02 UTC, fannypc11 commented on remote_payment_front/src/plugins/axios.js
Hecho

2022-03-19 01:02 UTC, fannypc11 commented on remote_payment_front/src/store/services/authService.js
> +      'http://localhost:3300/api/v1/auth/callback',
Hecho

2022-03-19 01:02 UTC, fannypc11 commented on remote_payment_front/src/store/services/authService.js
> +      localStorage.setItem('user', JSON.stringify(response.user));
Se creará un nuevo issue para realizar esta modificación

2022-03-23 21:04 UTC, merged