Feature: Create help page
wizeline/ror-remotepayment-wizeline pull request #97
Opened 2022-04-01 00:14 UTC by GabrielRendonP

# Created help page
- Added help page on page folder
- Added avatar component to display the support personal

@Apostat23

2022-04-01 20:13 UTC, georgexx009-wizeline requested changes
Great code, clean and simple (simplicity is the best 🚀 ), only one change to improve UX and also will help everyone if they need async behaviors, LMK if you have any question or I could help

2022-04-01 20:13 UTC, georgexx009-wizeline commented on remote_payment_front/src/pages/help/Help.jsx
> +function Help() {
The component looks great, easy to read, understandable, clean. 

Without a UX team, is our job to think beyond just code and think also in what the user will see. Currently, this component only handle success path, I would recommend to add logic to manage errors from the api and loading states to improve UX, both because we don't know how long the back will take to respond or if it is going to be a 2* status. Also, since async behavior is a common funcitonality, this is a great opportunity to create a custom hook :D check out this tutorial https://www.ankurkedia.com/blog/custom-hooks , reach me if you have any questions, I will be glad to help

2022-04-01 22:17 UTC, GabrielRendonP commented on remote_payment_front/src/pages/help/Help.jsx
> +function Help() {
Thanks for the feedback! Will move the fetch function to its own hook!

2022-04-08 18:30 UTC, georgexx009-wizeline requested changes

2022-04-08 18:30 UTC, georgexx009-wizeline commented on remote_payment_front/src/pages/help/Help.jsx
> +  const { data, loading, error } = useSelector((state) => state.finance);
if you don't need it, remove it, help have cleaner code, also with that we could remove the eslint disable

2022-04-08 18:30 UTC, georgexx009-wizeline commented on remote_payment_front/src/pages/help/Help.jsx
> +  const { data, loading, error } = useSelector((state) => state.finance);
what is data? and if it is a list, a list of what? meaningful names helps other people understand better the code without so much cognitive load

2022-04-08 18:30 UTC, georgexx009-wizeline commented on remote_payment_front/src/pages/help/Help.jsx
> +      {data !== null && data.length > 0 && (
you could use optional chaining to only have one condition, like data?.length > 0
I have a note for that https://www.craft.do/s/DYUTM7g3nzg3XI (extra tip, using optional chaining with nullish coalescing is a really good practice)

2022-04-08 18:30 UTC, georgexx009-wizeline commented on remote_payment_front/src/store/services/financeService.js
> +export const fetchMockData = createAsyncThunk(
good name, it will help us to modified when we make the change to consume the back. Another practice is to use the comment // TODO - , many IDEs takes this comments to create a to do list, and many teams manage their technical debt like this

2022-04-08 18:30 UTC, georgexx009-wizeline commented on remote_payment_front/src/store/slices/financeSlice.js
> +      state.error = '';
the default error type is null, besides an empty string is falsy, is a better practice to use null when we want to say that has nothing

2022-04-11 21:49 UTC, georgexx009-wizeline approved these changes
Awesome 🚀

2022-04-11 21:49 UTC, merged